### ISSUE TITLE
Package.json file is missing

### ISSUE THREAD

**Issue by jchu4483** [learn-co-students/angular-parsers-formatters-validators-lab-v-000#136]
Can't run npm install on this lab because package.json is missing. I re-forked twice but still the same problem. Can't run tests for this lab.

**Comment by aturkewi** [comment]
Thanks for raising this issue @jchu4483 . All set!

Also, in the future, the best place to raise issues on a lab is on the canonical versions of the lab (https://github.com/learn-co-curriculum/angular-parsers-formatters-validators-lab). You can find that by just clicking the raise issue icon in Learn (it'll bring you to the right spot)
